/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiPublicWarmupWorkerRouteImport } from './routes/api/public/warmup-worker'
import { Route as ApiPublicDispatchWorkerRouteImport } from './routes/api/public/dispatch-worker'
import { Route as AuthenticatedAppWarmupRouteImport } from './routes/_authenticated/app.warmup'
import { Route as AuthenticatedAppWalletRouteImport } from './routes/_authenticated/app.wallet'
import { Route as AuthenticatedAppServersRouteImport } from './routes/_authenticated/app.servers'
import { Route as AuthenticatedAppMarketplaceRouteImport } from './routes/_authenticated/app.marketplace'
import { Route as AuthenticatedAppListsRouteImport } from './routes/_authenticated/app.lists'
import { Route as AuthenticatedAppInstancesRouteImport } from './routes/_authenticated/app.instances'
import { Route as AuthenticatedAppInboxRouteImport } from './routes/_authenticated/app.inbox'
import { Route as AuthenticatedAppFlowsRouteImport } from './routes/_authenticated/app.flows'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppAntiBanRouteImport } from './routes/_authenticated/app.anti-ban'
import { Route as AuthenticatedAppFlowsIndexRouteImport } from './routes/_authenticated/app.flows.index'
import { Route as AuthenticatedAppCampaignsIndexRouteImport } from './routes/_authenticated/app.campaigns.index'
import { Route as ApiPublicEvolutionWebhookTokenRouteImport } from './routes/api/public/evolution-webhook.$token'
import { Route as AuthenticatedAppListsIdRouteImport } from './routes/_authenticated/app.lists.$id'
import { Route as AuthenticatedAppFlowsIdRouteImport } from './routes/_authenticated/app.flows.$id'
import { Route as AuthenticatedAppCampaignsNewRouteImport } from './routes/_authenticated/app.campaigns.new'
import { Route as AuthenticatedAppCampaignsIdRouteImport } from './routes/_authenticated/app.campaigns.$id'
import { Route as AuthenticatedAppAdminCatalogRouteImport } from './routes/_authenticated/app.admin.catalog'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWarmupWorkerRoute = ApiPublicWarmupWorkerRouteImport.update({
  id: '/api/public/warmup-worker',
  path: '/api/public/warmup-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDispatchWorkerRoute = ApiPublicDispatchWorkerRouteImport.update({
  id: '/api/public/dispatch-worker',
  path: '/api/public/dispatch-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppWarmupRoute = AuthenticatedAppWarmupRouteImport.update({
  id: '/app/warmup',
  path: '/app/warmup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppWalletRoute = AuthenticatedAppWalletRouteImport.update({
  id: '/app/wallet',
  path: '/app/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppServersRoute = AuthenticatedAppServersRouteImport.update({
  id: '/app/servers',
  path: '/app/servers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppMarketplaceRoute =
  AuthenticatedAppMarketplaceRouteImport.update({
    id: '/app/marketplace',
    path: '/app/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppListsRoute = AuthenticatedAppListsRouteImport.update({
  id: '/app/lists',
  path: '/app/lists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppInstancesRoute =
  AuthenticatedAppInstancesRouteImport.update({
    id: '/app/instances',
    path: '/app/instances',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppInboxRoute = AuthenticatedAppInboxRouteImport.update({
  id: '/app/inbox',
  path: '/app/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppFlowsRoute = AuthenticatedAppFlowsRouteImport.update({
  id: '/app/flows',
  path: '/app/flows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/app/billing',
  path: '/app/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAntiBanRoute = AuthenticatedAppAntiBanRouteImport.update({
  id: '/app/anti-ban',
  path: '/app/anti-ban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppFlowsIndexRoute =
  AuthenticatedAppFlowsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppFlowsRoute,
  } as any)
const AuthenticatedAppCampaignsIndexRoute =
  AuthenticatedAppCampaignsIndexRouteImport.update({
    id: '/app/campaigns/',
    path: '/app/campaigns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicEvolutionWebhookTokenRoute =
  ApiPublicEvolutionWebhookTokenRouteImport.update({
    id: '/api/public/evolution-webhook/$token',
    path: '/api/public/evolution-webhook/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppListsIdRoute = AuthenticatedAppListsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAppListsRoute,
} as any)
const AuthenticatedAppFlowsIdRoute = AuthenticatedAppFlowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAppFlowsRoute,
} as any)
const AuthenticatedAppCampaignsNewRoute =
  AuthenticatedAppCampaignsNewRouteImport.update({
    id: '/app/campaigns/new',
    path: '/app/campaigns/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCampaignsIdRoute =
  AuthenticatedAppCampaignsIdRouteImport.update({
    id: '/app/campaigns/$id',
    path: '/app/campaigns/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminCatalogRoute =
  AuthenticatedAppAdminCatalogRouteImport.update({
    id: '/app/admin/catalog',
    path: '/app/admin/catalog',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/anti-ban': typeof AuthenticatedAppAntiBanRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/flows': typeof AuthenticatedAppFlowsRouteWithChildren
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/instances': typeof AuthenticatedAppInstancesRoute
  '/app/lists': typeof AuthenticatedAppListsRouteWithChildren
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/app/servers': typeof AuthenticatedAppServersRoute
  '/app/wallet': typeof AuthenticatedAppWalletRoute
  '/app/warmup': typeof AuthenticatedAppWarmupRoute
  '/api/public/dispatch-worker': typeof ApiPublicDispatchWorkerRoute
  '/api/public/warmup-worker': typeof ApiPublicWarmupWorkerRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/catalog': typeof AuthenticatedAppAdminCatalogRoute
  '/app/campaigns/$id': typeof AuthenticatedAppCampaignsIdRoute
  '/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/app/flows/$id': typeof AuthenticatedAppFlowsIdRoute
  '/app/lists/$id': typeof AuthenticatedAppListsIdRoute
  '/api/public/evolution-webhook/$token': typeof ApiPublicEvolutionWebhookTokenRoute
  '/app/campaigns/': typeof AuthenticatedAppCampaignsIndexRoute
  '/app/flows/': typeof AuthenticatedAppFlowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/anti-ban': typeof AuthenticatedAppAntiBanRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/instances': typeof AuthenticatedAppInstancesRoute
  '/app/lists': typeof AuthenticatedAppListsRouteWithChildren
  '/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/app/servers': typeof AuthenticatedAppServersRoute
  '/app/wallet': typeof AuthenticatedAppWalletRoute
  '/app/warmup': typeof AuthenticatedAppWarmupRoute
  '/api/public/dispatch-worker': typeof ApiPublicDispatchWorkerRoute
  '/api/public/warmup-worker': typeof ApiPublicWarmupWorkerRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/catalog': typeof AuthenticatedAppAdminCatalogRoute
  '/app/campaigns/$id': typeof AuthenticatedAppCampaignsIdRoute
  '/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/app/flows/$id': typeof AuthenticatedAppFlowsIdRoute
  '/app/lists/$id': typeof AuthenticatedAppListsIdRoute
  '/api/public/evolution-webhook/$token': typeof ApiPublicEvolutionWebhookTokenRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsIndexRoute
  '/app/flows': typeof AuthenticatedAppFlowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/anti-ban': typeof AuthenticatedAppAntiBanRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/flows': typeof AuthenticatedAppFlowsRouteWithChildren
  '/_authenticated/app/inbox': typeof AuthenticatedAppInboxRoute
  '/_authenticated/app/instances': typeof AuthenticatedAppInstancesRoute
  '/_authenticated/app/lists': typeof AuthenticatedAppListsRouteWithChildren
  '/_authenticated/app/marketplace': typeof AuthenticatedAppMarketplaceRoute
  '/_authenticated/app/servers': typeof AuthenticatedAppServersRoute
  '/_authenticated/app/wallet': typeof AuthenticatedAppWalletRoute
  '/_authenticated/app/warmup': typeof AuthenticatedAppWarmupRoute
  '/api/public/dispatch-worker': typeof ApiPublicDispatchWorkerRoute
  '/api/public/warmup-worker': typeof ApiPublicWarmupWorkerRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/catalog': typeof AuthenticatedAppAdminCatalogRoute
  '/_authenticated/app/campaigns/$id': typeof AuthenticatedAppCampaignsIdRoute
  '/_authenticated/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/_authenticated/app/flows/$id': typeof AuthenticatedAppFlowsIdRoute
  '/_authenticated/app/lists/$id': typeof AuthenticatedAppListsIdRoute
  '/api/public/evolution-webhook/$token': typeof ApiPublicEvolutionWebhookTokenRoute
  '/_authenticated/app/campaigns/': typeof AuthenticatedAppCampaignsIndexRoute
  '/_authenticated/app/flows/': typeof AuthenticatedAppFlowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/anti-ban'
    | '/app/billing'
    | '/app/flows'
    | '/app/inbox'
    | '/app/instances'
    | '/app/lists'
    | '/app/marketplace'
    | '/app/servers'
    | '/app/wallet'
    | '/app/warmup'
    | '/api/public/dispatch-worker'
    | '/api/public/warmup-worker'
    | '/app/'
    | '/app/admin/catalog'
    | '/app/campaigns/$id'
    | '/app/campaigns/new'
    | '/app/flows/$id'
    | '/app/lists/$id'
    | '/api/public/evolution-webhook/$token'
    | '/app/campaigns/'
    | '/app/flows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/anti-ban'
    | '/app/billing'
    | '/app/inbox'
    | '/app/instances'
    | '/app/lists'
    | '/app/marketplace'
    | '/app/servers'
    | '/app/wallet'
    | '/app/warmup'
    | '/api/public/dispatch-worker'
    | '/api/public/warmup-worker'
    | '/app'
    | '/app/admin/catalog'
    | '/app/campaigns/$id'
    | '/app/campaigns/new'
    | '/app/flows/$id'
    | '/app/lists/$id'
    | '/api/public/evolution-webhook/$token'
    | '/app/campaigns'
    | '/app/flows'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/anti-ban'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/flows'
    | '/_authenticated/app/inbox'
    | '/_authenticated/app/instances'
    | '/_authenticated/app/lists'
    | '/_authenticated/app/marketplace'
    | '/_authenticated/app/servers'
    | '/_authenticated/app/wallet'
    | '/_authenticated/app/warmup'
    | '/api/public/dispatch-worker'
    | '/api/public/warmup-worker'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/catalog'
    | '/_authenticated/app/campaigns/$id'
    | '/_authenticated/app/campaigns/new'
    | '/_authenticated/app/flows/$id'
    | '/_authenticated/app/lists/$id'
    | '/api/public/evolution-webhook/$token'
    | '/_authenticated/app/campaigns/'
    | '/_authenticated/app/flows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicDispatchWorkerRoute: typeof ApiPublicDispatchWorkerRoute
  ApiPublicWarmupWorkerRoute: typeof ApiPublicWarmupWorkerRoute
  ApiPublicEvolutionWebhookTokenRoute: typeof ApiPublicEvolutionWebhookTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/warmup-worker': {
      id: '/api/public/warmup-worker'
      path: '/api/public/warmup-worker'
      fullPath: '/api/public/warmup-worker'
      preLoaderRoute: typeof ApiPublicWarmupWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dispatch-worker': {
      id: '/api/public/dispatch-worker'
      path: '/api/public/dispatch-worker'
      fullPath: '/api/public/dispatch-worker'
      preLoaderRoute: typeof ApiPublicDispatchWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/warmup': {
      id: '/_authenticated/app/warmup'
      path: '/app/warmup'
      fullPath: '/app/warmup'
      preLoaderRoute: typeof AuthenticatedAppWarmupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/wallet': {
      id: '/_authenticated/app/wallet'
      path: '/app/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AuthenticatedAppWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/servers': {
      id: '/_authenticated/app/servers'
      path: '/app/servers'
      fullPath: '/app/servers'
      preLoaderRoute: typeof AuthenticatedAppServersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/marketplace': {
      id: '/_authenticated/app/marketplace'
      path: '/app/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AuthenticatedAppMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lists': {
      id: '/_authenticated/app/lists'
      path: '/app/lists'
      fullPath: '/app/lists'
      preLoaderRoute: typeof AuthenticatedAppListsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/instances': {
      id: '/_authenticated/app/instances'
      path: '/app/instances'
      fullPath: '/app/instances'
      preLoaderRoute: typeof AuthenticatedAppInstancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/inbox': {
      id: '/_authenticated/app/inbox'
      path: '/app/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AuthenticatedAppInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/flows': {
      id: '/_authenticated/app/flows'
      path: '/app/flows'
      fullPath: '/app/flows'
      preLoaderRoute: typeof AuthenticatedAppFlowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/app/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/anti-ban': {
      id: '/_authenticated/app/anti-ban'
      path: '/app/anti-ban'
      fullPath: '/app/anti-ban'
      preLoaderRoute: typeof AuthenticatedAppAntiBanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/flows/': {
      id: '/_authenticated/app/flows/'
      path: '/'
      fullPath: '/app/flows/'
      preLoaderRoute: typeof AuthenticatedAppFlowsIndexRouteImport
      parentRoute: typeof AuthenticatedAppFlowsRoute
    }
    '/_authenticated/app/campaigns/': {
      id: '/_authenticated/app/campaigns/'
      path: '/app/campaigns'
      fullPath: '/app/campaigns/'
      preLoaderRoute: typeof AuthenticatedAppCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/evolution-webhook/$token': {
      id: '/api/public/evolution-webhook/$token'
      path: '/api/public/evolution-webhook/$token'
      fullPath: '/api/public/evolution-webhook/$token'
      preLoaderRoute: typeof ApiPublicEvolutionWebhookTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/lists/$id': {
      id: '/_authenticated/app/lists/$id'
      path: '/$id'
      fullPath: '/app/lists/$id'
      preLoaderRoute: typeof AuthenticatedAppListsIdRouteImport
      parentRoute: typeof AuthenticatedAppListsRoute
    }
    '/_authenticated/app/flows/$id': {
      id: '/_authenticated/app/flows/$id'
      path: '/$id'
      fullPath: '/app/flows/$id'
      preLoaderRoute: typeof AuthenticatedAppFlowsIdRouteImport
      parentRoute: typeof AuthenticatedAppFlowsRoute
    }
    '/_authenticated/app/campaigns/new': {
      id: '/_authenticated/app/campaigns/new'
      path: '/app/campaigns/new'
      fullPath: '/app/campaigns/new'
      preLoaderRoute: typeof AuthenticatedAppCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/campaigns/$id': {
      id: '/_authenticated/app/campaigns/$id'
      path: '/app/campaigns/$id'
      fullPath: '/app/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedAppCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/catalog': {
      id: '/_authenticated/app/admin/catalog'
      path: '/app/admin/catalog'
      fullPath: '/app/admin/catalog'
      preLoaderRoute: typeof AuthenticatedAppAdminCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAppFlowsRouteChildren {
  AuthenticatedAppFlowsIdRoute: typeof AuthenticatedAppFlowsIdRoute
  AuthenticatedAppFlowsIndexRoute: typeof AuthenticatedAppFlowsIndexRoute
}

const AuthenticatedAppFlowsRouteChildren: AuthenticatedAppFlowsRouteChildren = {
  AuthenticatedAppFlowsIdRoute: AuthenticatedAppFlowsIdRoute,
  AuthenticatedAppFlowsIndexRoute: AuthenticatedAppFlowsIndexRoute,
}

const AuthenticatedAppFlowsRouteWithChildren =
  AuthenticatedAppFlowsRoute._addFileChildren(
    AuthenticatedAppFlowsRouteChildren,
  )

interface AuthenticatedAppListsRouteChildren {
  AuthenticatedAppListsIdRoute: typeof AuthenticatedAppListsIdRoute
}

const AuthenticatedAppListsRouteChildren: AuthenticatedAppListsRouteChildren = {
  AuthenticatedAppListsIdRoute: AuthenticatedAppListsIdRoute,
}

const AuthenticatedAppListsRouteWithChildren =
  AuthenticatedAppListsRoute._addFileChildren(
    AuthenticatedAppListsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAntiBanRoute: typeof AuthenticatedAppAntiBanRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppFlowsRoute: typeof AuthenticatedAppFlowsRouteWithChildren
  AuthenticatedAppInboxRoute: typeof AuthenticatedAppInboxRoute
  AuthenticatedAppInstancesRoute: typeof AuthenticatedAppInstancesRoute
  AuthenticatedAppListsRoute: typeof AuthenticatedAppListsRouteWithChildren
  AuthenticatedAppMarketplaceRoute: typeof AuthenticatedAppMarketplaceRoute
  AuthenticatedAppServersRoute: typeof AuthenticatedAppServersRoute
  AuthenticatedAppWalletRoute: typeof AuthenticatedAppWalletRoute
  AuthenticatedAppWarmupRoute: typeof AuthenticatedAppWarmupRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppAdminCatalogRoute: typeof AuthenticatedAppAdminCatalogRoute
  AuthenticatedAppCampaignsIdRoute: typeof AuthenticatedAppCampaignsIdRoute
  AuthenticatedAppCampaignsNewRoute: typeof AuthenticatedAppCampaignsNewRoute
  AuthenticatedAppCampaignsIndexRoute: typeof AuthenticatedAppCampaignsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAntiBanRoute: AuthenticatedAppAntiBanRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppFlowsRoute: AuthenticatedAppFlowsRouteWithChildren,
  AuthenticatedAppInboxRoute: AuthenticatedAppInboxRoute,
  AuthenticatedAppInstancesRoute: AuthenticatedAppInstancesRoute,
  AuthenticatedAppListsRoute: AuthenticatedAppListsRouteWithChildren,
  AuthenticatedAppMarketplaceRoute: AuthenticatedAppMarketplaceRoute,
  AuthenticatedAppServersRoute: AuthenticatedAppServersRoute,
  AuthenticatedAppWalletRoute: AuthenticatedAppWalletRoute,
  AuthenticatedAppWarmupRoute: AuthenticatedAppWarmupRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppAdminCatalogRoute: AuthenticatedAppAdminCatalogRoute,
  AuthenticatedAppCampaignsIdRoute: AuthenticatedAppCampaignsIdRoute,
  AuthenticatedAppCampaignsNewRoute: AuthenticatedAppCampaignsNewRoute,
  AuthenticatedAppCampaignsIndexRoute: AuthenticatedAppCampaignsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicDispatchWorkerRoute: ApiPublicDispatchWorkerRoute,
  ApiPublicWarmupWorkerRoute: ApiPublicWarmupWorkerRoute,
  ApiPublicEvolutionWebhookTokenRoute: ApiPublicEvolutionWebhookTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
